from PIL import Image,ImageOps
import os,sys,bitplanelib,math

from shared import *

import generate_tiles



generated_message = "* generated by convert_graphics.py\n"
dump_it = True



if dump_it:
    if not os.path.exists(dump_dir):
        os.mkdir(dump_dir)
        with open(os.path.join(dump_dir,".gitignore"),"w") as f:
            f.write("*")


def dump_asm_bytes(*args,**kwargs):
    bitplanelib.dump_asm_bytes(*args,**kwargs,mit_format=True)


def ensure_empty(d):
    if d.exists():
        for f in os.listdir(d):
            os.remove(os.path.join(d,f))
    else:
        d.mkdir(parents=True)


possible_hw_sprites = set()

def dump_bob_layer(sprite_table,f,default_prefix="bob",sprite_names=None,relative_root=None,context=None):
    if relative_root:
        f.write(f"{relative_root}:\n")
    for i,tile_entry in enumerate(sprite_table):
        f.write("\t.long\t")
        if i not in possible_hw_sprites and any(tile_entry):
            prefix = default_prefix if not sprite_names else sprite_names.get(i,default_prefix)
            f.write(f"{prefix}_{i:02x}")
            if relative_root:
                f.write(f"-{relative_root}")

        else:
            f.write("0")
        f.write("\n")


    for i,tile_entry in enumerate(sprite_table):
        if i not in possible_hw_sprites and any(tile_entry):
            prefix = default_prefix if not sprite_names else sprite_names.get(i,default_prefix)
            if True:
                f.write(f"{prefix}_{i:02x}:\n")
                for j,t in enumerate(tile_entry):
                    f.write("\t.long\t")
                    if t:
                        f.write(f"{prefix}_{i:02x}_{j:02x}")
                        if relative_root:
                            f.write(f"-{relative_root}")
                    else:
                        f.write("0")
                    f.write("\n")

    needed_bob_bitplanes = set()

    for i,tile_entry in enumerate(sprite_table):
        if i not in possible_hw_sprites and any(tile_entry):
            prefix = sprite_names.get(i,"bob")
            if True:
                for j,t in enumerate(tile_entry):
                    if t:
                        name = f"{prefix}_{i:02x}_{j:02x}"

                        f.write(f"{name}:\n")
                        height = 0

                        offset = 0
                        for orientation,_ in plane_orientations:
                            if orientation in t:
                                width = t[orientation]["width"]
                                height = t[orientation]["height"]
                                offset = t[orientation]["y_start"]
                                break
                        else:
                            raise Exception(f"height not found for {name}!!")
                        nonzero_written = False
                        for orientation,_ in plane_orientations:
                            # loop for this, this sucks
                            if orientation == "standard":
                                f.write("* orientation={}\n".format(orientation))
                                active_planes = 0
                                bitplanes = t[orientation]["bitplanes"]

                                for j,bitplane_id in enumerate(bitplanes):
                                    if bitplane_id:
                                        active_planes |= 1<<j
                                bitplane_info = f"\t.word\t{height},{width},{offset},0x{active_planes:x}  | height,width,offset,active_planes\n"
                                f.write(bitplane_info)
                                for bitplane_id in bitplanes:
                                    f.write("\t.long\t")
                                    if bitplane_id:
                                        nonzero_written = True
                                        bob_bitplane_ptr = f"bob_plane_{bitplane_id:02d}"
                                        needed_bob_bitplanes.add(bitplane_id)
                                        f.write(bob_bitplane_ptr)
                                        if relative_root:
                                            f.write(f"-{relative_root}")
                                    else:
                                        f.write("0")
                                    f.write("\n")

                        if nonzero_written and False:
                            # tell the game engine that it has to mirror the bitplanes
                            # at start/file load and put them here
                            # (except if tile has 0 data because it's blank)

                            f.write("* mirrored bitplanes pointers (inc. mask) go here\n")
                            for _ in bitplanes:
                                f.write(f"\t.long\t-1\n")
                        else:
                            # tell the game engine that it has to mirror in-place
                            f.write("\t.word\t-2    | bitplanes above will be mirrored in-place\n\n")

    if not relative_root:
        f.write("end_tables:\n\t.section\t.datachip\n")

    for k,v in bob_plane_cache.items():
        if v in needed_bob_bitplanes:
            f.write(f"""
\t.word\t0    | plane {v:02d} orientation
bob_plane_{v:02d}:""")
            dump_asm_bytes(k,f)

def load_tileset(image_name,palette_index,width,height,tileset_name,dumpdir,
dump=False,name_dict=None,cluts=None,tile_number=0,is_bob=False):

##    if isinstance(image_name,str):
##        full_image_path = os.path.join(this_dir,os.path.pardir,"sheets",
##                            tile_type,image_name)
##        tiles_1 = Image.open(full_image_path)
##    else:
    tiles_1 = image_name
    nb_rows = tiles_1.size[1] // height
    nb_cols = tiles_1.size[0] // width


    tileset_1 = []

    if dump:
        dump_subdir = dumpdir / tileset_name
        if palette_index == 0 and tile_number == 0:
            ensure_empty(dump_subdir)

    palette = set()

    for j in range(nb_rows):
        for i in range(nb_cols):
            if cluts is not None and (tile_number not in cluts or palette_index not in cluts[tile_number]):
                # no clut declared for that tile
                tileset_1.append(None)
            else:

                img = Image.new("RGB",(width,height))
                img.paste(tiles_1,(-i*width,-j*height))


                # only consider colors of used tiles
                palette.update(set(bitplanelib.palette_extract(img)))


                tileset_1.append(img)
                # dump tiles
                if dump:
                    img = ImageOps.scale(img,5,resample=Image.Resampling.NEAREST)
                    if name_dict:
                        name = name_dict.get(tile_number,"unknown")
                    else:
                        name = "unknown"

                    img.save(os.path.join(dump_subdir,f"{name}_{tile_number:02x}_{palette_index:02x}.png"))
            tile_number += 1

    return sorted(set(palette)),tileset_1

all_tile_cluts = False



fg_tile_cluts = {}
bg_tile_cluts = {}

total_nb_colors = 8

read_used_tiles("fg_used_tiles",fg_tile_cluts,FG_NB_TILES,FG_NB_CLUTS)



# now gather all cluts used by letter/digit tiles, logging probably
# missed some
# some tiles are hard to display... We know they are there, we force them
# instead of trying to trigger them by playing to death :)

alphanum_tile_codes = list(range(0,0x40))
used_cluts = set()
for atc in alphanum_tile_codes:
    cluts = fg_tile_cluts.get(atc)
    if cluts:
        used_cluts.update(cluts)
# now set cluts for all alphanum tiles
for atc in alphanum_tile_codes:
    fg_tile_cluts[atc] = sorted(used_cluts)


plane_orientations = [("standard",lambda x:x),
("flip",ImageOps.flip),
("mirror",ImageOps.mirror),
("flip_mirror",lambda x:ImageOps.flip(ImageOps.mirror(x)))]




def read_tileset(img_set_list,palette,plane_orientation_flags,cache,is_bob,nb_cluts,mask_color,next_cache_id = 1):
    nb_planes = int(math.log2(len(palette)))
    tile_table = []
    for n,img_set in enumerate(img_set_list):
        tile_entry = []
        for i,tile in enumerate(img_set):
            entry = dict()
            if tile:

                for b,(plane_name,plane_func) in zip(plane_orientation_flags,plane_orientations):
                    bitplane_sprite_data = None
                    if b:

                        actual_nb_planes = nb_planes

                        # most sprites aren't mirrored. Save a lot of memory!
                        if plane_func == ImageOps.mirror and i not in mirror_sprites:
                            continue

                        wtile = plane_func(tile)

                        if is_bob:
                            actual_nb_planes += 1


                            # only 4 planes + mask => 5 planes
                            orig_wtile = wtile
                            y_start,wtile = bitplanelib.autocrop_y(wtile,mask_color=magenta)
                            height = wtile.size[1]
                            width = wtile.size[0]//8 + 2
                            bitplane_data = bitplanelib.palette_image2raw(wtile,None,palette,generate_mask=True,mask_color=mask_color)
                            # add sprite data if eligible: player frame, not mirrored

##                            if i in possible_hw_sprites:
##                                # using original, uncropped bitplane data
##                                bitplane_sprite_data = bitplanelib.palette_image2attached_sprites(orig_wtile,None,palette,
##                                sprite_fmode=2,with_control_words=True)
##                                # void the blitter data
##                                bitplane_data = b''
                        else:
                            # 4 planes, no mask
                            height = 8
                            width = 1
                            y_start = 0
                            bitplane_data = bitplanelib.palette_image2raw(wtile,None,palette,mask_color=mask_color)

                        plane_size = len(bitplane_data) // actual_nb_planes

                        bitplane_plane_ids = []
                        for j in range(actual_nb_planes):
                            offset = j*plane_size
                            bitplane = bitplane_data[offset:offset+plane_size]

                            cache_id = cache.get(bitplane)
                            if cache_id is not None:
                                bitplane_plane_ids.append(cache_id)
                            else:
                                if any(bitplane):
                                    cache[bitplane] = next_cache_id
                                    bitplane_plane_ids.append(next_cache_id)
                                    next_cache_id += 1
                                else:
                                    bitplane_plane_ids.append(0)  # blank
                        entry[plane_name] = {"width":width,"height":height,"y_start":y_start,"bitplanes":bitplane_plane_ids}
                        if bitplane_sprite_data:
                            entry[plane_name]["sprdat"] = bitplane_sprite_data

            tile_entry.append(entry)

        tile_table.append(tile_entry)

    new_tile_table = [[[] for _ in range(nb_cluts)] for _ in range(len(tile_table[0]))]

    # reorder/transpose. We have 16 * 256 we need 256 * 16
    for i,u in enumerate(tile_table):
        for j,v in enumerate(u):
            new_tile_table[j][i] = v

    return new_tile_table,next_cache_id


def dump_tile_layer(tile_table,prefix,tile_plane_prefix=None,relative_root=None):
    item_decl = "\t.long\t"
    tile_plane_prefix = tile_plane_prefix or prefix
    if relative_root:
        f.write(f"{relative_root}:\n")
    for i,tile_entry in enumerate(tile_table):
        f.write(item_decl)
        if tile_entry and any(tile_entry):
            f.write(f"{prefix}tile_{i:02x}")
            if relative_root:
                f.write(f"-{relative_root}")
        else:
            f.write("0")
        f.write("\n")

    for i,tile_entry in enumerate(tile_table):
        if tile_entry and any(tile_entry):
            rr = f"{prefix}tile_{i:02x}"
            f.write(f"{rr}:\n")
            for j,t in enumerate(tile_entry):
                f.write(item_decl)
                if t:
                    f.write(f"{prefix}tile_{i:02x}_{j:02x}")
                    if relative_root:
                        f.write(f"-{relative_root}")
                else:
                    f.write("0")
                f.write("\n")


    for i,tile_entry in enumerate(tile_table):
        if tile_entry and any(tile_entry):
            for j,t in enumerate(tile_entry):
                if t:
                    name = f"{prefix}tile_{i:02x}_{j:02x}"

                    f.write(f"{name}:\n")
                    for orientation,_ in plane_orientations:
                        f.write("* orientation={}\n".format(orientation))
                        if orientation in t:
                            data = t[orientation]
                            for bitplane_id in data["bitplanes"]:
                                f.write(item_decl)
                                if bitplane_id:
                                    f.write(f"{tile_plane_prefix}tile_plane_{bitplane_id:02d}")
                                    if relative_root:
                                        f.write(f"-{relative_root}")
                                else:
                                    f.write("0")
                                f.write("\n")
                            if len(t)==1:
                                # optim: only standard
                                break
                        else:
                            for _ in range(nb_planes):
                                f.write(f"{item_decl}0\n")
    return i+1


def apply_color_replacement(sprite_set_list,quantized):
    """ change colors for list of tilesets (tiles, sprites)
    quantized: RGB => RGB color replacement dictionary
    """

    for sset in sprite_set_list:
        for tile in sset:
            if tile:
                bitplanelib.replace_color_from_dict(tile,quantized)

def quantize_palette(rgb_tuples,img_type,nb_quantize,transparent=None,dump_it=False):
    rgb_configs = set(rgb_tuples)

    nb_target_colors = nb_quantize
    if transparent:
        rgb_configs.remove(transparent)
        # remove black, white, we don't want it quantized
        immutable_colors = (transparent,black)
    else:
        immutable_colors = (black,)

    for c in immutable_colors:
        rgb_configs.discard(c)
        nb_quantize -= 1

    dump_graphics = False
    # now compose an image with the colors
    clut_img = Image.new("RGB",(len(rgb_configs),1))
    for i,rgb in enumerate(rgb_configs):
        #rgb_value = (rgb[0]<<16)+(rgb[1]<<8)+rgb[2]
        clut_img.putpixel((i,0),rgb)

    reduced_colors_clut_img = clut_img.quantize(colors=nb_quantize,dither=0).convert('RGB')

    # get the reduced palette
    reduced_palette = [reduced_colors_clut_img.getpixel((i,0)) for i,_ in enumerate(rgb_configs)]
    # apply rounding now, else possible color duplicates, which would be a pity
    reduced_palette = bitplanelib.palette_round(reduced_palette,0xF0)

    # now create a dictionary by associating the original & reduced colors
    rval = dict(zip(rgb_configs,reduced_palette))

    # add black & white & transparent back
    for c in immutable_colors:
        rval[c] = c


    if dump_it:  # debug it, create 2 rows, 1 non-quantized, and 1 quantized, separated by bloack
        s = clut_img.size
        ns = (s[0]*30,s[1]*30)
        clut_img = clut_img.resize(ns,resample=0)
        whole_image = Image.new("RGB",(clut_img.size[0],clut_img.size[1]*3))
        whole_image.paste(clut_img,(0,0))
        reduced_colors_clut_img = reduced_colors_clut_img.resize(ns,resample=0)
        whole_image.paste(reduced_colors_clut_img,(0,clut_img.size[1]*2))
        whole_image.save(dump_dir / "{}_colors.png".format(img_type))

    result_nb = len(set(reduced_palette))
    if nb_quantize < result_nb:
        raise Exception(f"quantize: {img_type}: {nb_quantize} expected, found {result_nb}")
    # return it
    return rval



if dump_it:
    if not all_tile_cluts:
        with open(dump_dir / "used_fg_tiles.json","w") as f:
            fg_tile_cluts_dict = {hex(k):[hex(x) for x in v] for k,v in fg_tile_cluts.items() if v}
            json.dump(fg_tile_cluts_dict,f,indent=2)



bg_tile_palette = set()
fg_tile_palette = set()

fg_tile_sheet_dict = {i:img for i,img in enumerate(generate_tiles.doit_fg_tiles())}

rom_tiles_dict = generate_tiles.doit_rom_tiles()
###############
# foreground
###############
fg_tile_set_list = []

for i,tsd in fg_tile_sheet_dict.items():
    _,tile_set = load_tileset(tsd,i,8,8,"fg_tiles",dump_dir,dump=dump_it,
    cluts=fg_tile_cluts,
    name_dict=None)

    # we need to separate the palettes for OSD because 1) there are too many of them and quantize sucks
    # and 2) the colors of the weapons in the panel is dynamic

    upper_tile_set = [None] * len(tile_set)
    for j,tile in enumerate(tile_set):
        tp = set()
        if tile:
            tp = set(bitplanelib.palette_extract(tile))
            fg_tile_palette.update(tp)
            upper_tile_set[j] = tile

    fg_tile_set_list.append(upper_tile_set)


# we'll quantize manually, 21 FG colors => 18
fg_replacement_dict = {(0,184,151):(0,0,222)
}
apply_color_replacement(fg_tile_set_list,fg_replacement_dict)

# also change colors of ROM tiles
apply_color_replacement(rom_tiles_dict["body"].values(),fg_replacement_dict)
# also change colors of ROM tiles
##for p in rom_tiles_dict["head"].values():
##    apply_color_replacement(p,fg_replacement_dict)

# fg_tile_set_list is a 8x256 matrix (clut x tile)
# rom_tiles_dict is a dictionary: tile_data_address => 8 cluts
# to use the same data to asm file routines, we need to "transpose" the data to have
# a table of 8 cluts pointing to each tile. The addresses are not indexes, so it's more complex
# but they can still be sorted

# create a structure compatible with the bitplane converting/dumping tools
# that we use for lots of games on fixed rom charsets
# clut => images (8 cluts, 24 different possible images)
# result: 8*24 pic matrix
rom_body_tile_set_list = [[] for _ in range(8)]
for key,data in sorted(rom_tiles_dict["body"].items()):
    for d,outl in zip(data,rom_body_tile_set_list):
        outl.append(d)

# clut => image sets (8 cluts, 24 different possible image sets, 9 images per set)
# we should flatten the 2 last dimensions to remain compatible with the dumping tools
# result: 8*216 pic matrix
##rom_head_tile_set_list = [[] for _ in range(8)]
##for key,data in sorted(rom_tiles_dict["head"].items()):
##    for d,outl in zip(data,rom_head_tile_set_list):
##        outl.extend(d)


# recompute new fg palette
fg_tile_palette = set()

for tile_set in fg_tile_set_list:
    for j,tile in enumerate(tile_set):
        tp = set()
        if tile:
            tp = set(bitplanelib.palette_extract(tile))
            fg_tile_palette.update(tp)

# then lazy me let's quantize 18=>16


# don't change the white position leave it as last else game colors
# will be screwed (copper dyn change + bitplane change on diamond snake body)
fg_tile_palette = sorted(fg_tile_palette)

# kill head/tail tiles
for t in list(range(0x31,0x3A))+list(range(0x61,0x6A))+[0x4B,0x49,0x4D]:
    for fg_tile_set in fg_tile_set_list:
        fg_tile_set[t] = None

# load pics for head & tail

def load_pic(name):
    img_right = Image.open(sheets_path / name)
    x_padded,y_padded = img_right.size
    if x_padded % 16:
        x_padded = ((x_padded//16)+1)*16
    if y_padded % 16:
        y_padded = ((y_padded//16)+1)*16

    nimg = Image.new("RGB",(x_padded,y_padded))
    nimg.paste(img_right)
    img_right = nimg

    img_list = [img_right]
    img_list.append(img_right.transpose(Image.Transpose.FLIP_LEFT_RIGHT))  # face left
    img_list.append(img_right.transpose(Image.Transpose.ROTATE_90))  # face down
    img_list.append(img_list[-1].transpose(Image.Transpose.FLIP_TOP_BOTTOM))  # up
    if dump_it:
        part_dir = dump_dir / "parts"
        part_dir.mkdir(exist_ok=True)
        for i,img in enumerate(img_list):
            img = ImageOps.scale(img,5,resample=Image.Resampling.NEAREST)
            img.save(part_dir / f"{pathlib.Path(name).stem}_{i}.png")
    return img_list

sprite_images = load_pic("head.png") + load_pic("tail_straight.png") + load_pic("tail_crooked.png") + load_pic("head_mask.png") + load_pic("tail_mask.png")

bob_plane_cache = {}

sprite_table,_ = read_tileset([sprite_images],fg_tile_palette,plane_orientation_flags=[True,False,False,False],
                    cache=bob_plane_cache,is_bob=True,nb_cluts=1,mask_color=black)


###############
# background
###############

bg_tile_sheet_dict = {i:img for i,img in enumerate(generate_tiles.doit_bg_tiles())}

read_used_tiles("bg_used_tiles",bg_tile_cluts,BG_NB_TILES,BG_NB_CLUTS)

bg_tile_set_list = []


for i,tsd in bg_tile_sheet_dict.items():
    tp,tile_set = load_tileset(tsd,i,8,8,"bg_tiles",dump_dir,dump=dump_it,
    cluts=bg_tile_cluts,
    name_dict=None)

    bg_tile_set_list.append(tile_set)
    bg_tile_palette.update(tp)



target_nb_colors = total_nb_colors
if len(bg_tile_palette)>target_nb_colors:
    print(f"Too many colors ({len(bg_tile_palette)}), quantizing")
    bitplanelib.palette_dump(bg_tile_palette,dump_dir / "bg_tile_palette_orig.png",pformat=bitplanelib.PALETTE_FORMAT_PNG)
    for attempt_nb_colors in [target_nb_colors+3,target_nb_colors+2,target_nb_colors+1,target_nb_colors]:
        bg_replacement_dict = quantize_palette(bg_tile_palette,"foreground_upper_tiles",attempt_nb_colors,transparent=black,dump_it=dump_it)
        new_bg_tile_palette = sorted(set(bg_replacement_dict.values()))
        if len(new_bg_tile_palette)<=target_nb_colors:
            print(f"Quantization achieved {len(new_bg_tile_palette)} colors with start colors = {attempt_nb_colors}")
            bg_tile_palette = new_bg_tile_palette
            break
    else:
        raise Exception("quantize error")  # not really possible since we try 32 as last chance!
    apply_color_replacement(bg_tile_set_list,bg_replacement_dict)
    bg_tile_palette = sorted(set(bg_replacement_dict.values()))
    bitplanelib.palette_dump(bg_tile_palette,dump_dir / "bg_tile_palette_after.png",pformat=bitplanelib.PALETTE_FORMAT_PNG)
else:
    pass

bg_tile_palette = sorted(bg_tile_palette)





print(f"Used bg tile colors: {len(bg_tile_palette)}")

# pad to x colors

bg_tile_palette+= (total_nb_colors-len(bg_tile_palette)) * [(0x10,0x20,0x30)]
fg_tile_palette+= (total_nb_colors-len(fg_tile_palette)) * [(0x10,0x20,0x30)]

if dump_it:
    if not all_tile_cluts:
        with open(dump_dir / "used_fg_tiles.json","w") as f:
            fg_tile_cluts_dict = {hex(k):[hex(x) for x in v] for k,v in fg_tile_cluts.items() if v}
            json.dump(fg_tile_cluts_dict,f,indent=2)
        dump_dir.mkdir(exist_ok=True)
        with open(dump_dir / "used_bg_tiles.json","w") as f:
            bg_tile_cluts_dict = {hex(k):[hex(x) for x in v] for k,v in bg_tile_cluts.items() if v}
            json.dump(bg_tile_cluts_dict,f,indent=2)

bg_tile_plane_cache = {}

bg_tile_table,_ = read_tileset(bg_tile_set_list,bg_tile_palette,[True,False,False,False],cache=bg_tile_plane_cache,
is_bob=False, nb_cluts=BG_NB_CLUTS, mask_color=magenta)




tile_plane_cache = {}

fg_tile_table,next_cache_id = read_tileset(fg_tile_set_list,fg_tile_palette,[True,False,False,False],cache=tile_plane_cache, is_bob=False,
mask_color=black, nb_cluts=FG_NB_CLUTS)
rom_body_tile_table,next_cache_id = read_tileset(rom_body_tile_set_list,fg_tile_palette,[True,False,False,False],cache=tile_plane_cache,
is_bob=False, nb_cluts=FG_NB_CLUTS, mask_color=black, next_cache_id=next_cache_id)
##rom_head_tile_table,next_cache_id = read_tileset(rom_head_tile_set_list,fg_tile_palette,[True,False,False,False],cache=tile_plane_cache,
##is_bob=False, nb_cluts=FG_NB_CLUTS, mask_color=black, next_cache_id=next_cache_id)


with open(src_dir / "palette.68k","w") as f:
    f.write(generated_message)
    f.write("bg_tile_palette:\n")
    bitplanelib.palette_dump(bg_tile_palette,f,bitplanelib.PALETTE_FORMAT_ASMGNU)
    f.write("fg_tile_palette:\n")
    bitplanelib.palette_dump(fg_tile_palette,f,bitplanelib.PALETTE_FORMAT_ASMGNU)



with open(src_dir / "graphics.68k","w") as f:
    f.write(generated_message)
    f.write("\t.global\tfg_character_table\n")
    f.write("\t.global\tbg_character_table\n")
    f.write("\t.global\trom_character_table\n")
    f.write("\t.global\tbob_table\n")
    f.write("\t.global\tend_tables\n")
    f.write("fg_character_table:\n")

    offset = dump_tile_layer(fg_tile_table,"fg_")

    # ROM tables, not as easy as fg/bg tiles, more convoluted because we want to
    # use the same tile dump system with reusable planes, etc. but we don't have
    # the same start structure
    # the game copies data from one address starting at 0x6000 (the key here) to
    # potentially any character
    # key is address-0x6000 divided by 8

    address_table = [None]*0x200  # should be enough

    f.write("rom_character_table:\n")
    # the order is the same, but we need to retrieve the addresses to serve as keys
    # for body parts there's 1 pic per address
    for idx,address in enumerate(sorted(rom_tiles_dict["body"])):
        key = (address-0x6000)//8
        address_table[key] = f"rom_body_tile_index_table+0x{idx*4:02x} | 0x{address:04x} (body)"

    # for head parts there are 9 pics per address (mirroring not supported right now)
##    for idx,address in enumerate(sorted(rom_tiles_dict["head"])):
##        key = (address-0x6000)//8
##        for i in range(9):
##            offset = (idx*9+i)*4
##            address_table[key+i] = f"rom_head_tile_index_table+0x{offset:02x} | 0x{address+8*i:04x} (head_char_index={i})"

    for a in address_table:
        f.write("\t.long\t")
        if a:
            f.write(a)
        else:
            f.write("0")
        f.write("\n")

    f.write("\n* ROM tiles (body)\n\n")
    f.write("rom_body_tile_index_table:\n")
    dump_tile_layer(rom_body_tile_table,f"rom_body_",tile_plane_prefix="fg_")
##    f.write("\n* ROM tiles (head)\n\n")
##    f.write("rom_head_tile_index_table:\n")
##    dump_tile_layer(rom_head_tile_table,f"rom_head_",tile_plane_prefix="fg_")

    for k,v in tile_plane_cache.items():
        f.write(f"fg_tile_plane_{v:02d}:")
        dump_asm_bytes(k,f)

    f.write("bg_character_table:\n")
    dump_tile_layer(bg_tile_table,"bg_")
    for k,v in bg_tile_plane_cache.items():
        f.write(f"bg_tile_plane_{v:02d}:")
        dump_asm_bytes(k,f)

    f.write("bob_table:\n")
    sprite_names = {}
    for i in range(4):
        sprite_names[i] = "head"
    for i in range(4,8):
        sprite_names[i] = "tail_straight"
    for i in range(8,12):
        sprite_names[i] = "tail_crooked"
    for i in range(12,16):
        sprite_names[i] = "head_mask"
    for i in range(16,20):
        sprite_names[i] = "tail_mask"
    dump_bob_layer(sprite_table,f,sprite_names=sprite_names)



